#!/usr/bin/env bash

. hooks/CONFIG

WORKING_DIR=$PRE_RECEIVE_DIR

while read oldrev newrev refname
do
	cleanDir $WORKING_DIR
	mkdir -p $WORKING_DIR
	git archive --format=tar $newrev | (cd $WORKING_DIR && tar xf -)

	# check js
	checkJsWords

	# check php
	checkPhpWords

	# php -l
	phpSyntaxCheck

	# phpcs
	phpCodeSniffingCheck
done

exit 0
